In [1]:
import numpy as np

In [2]:
print("Numpy Package Version", np.__version__)

Numpy Package Version 1.21.6


# Performance Compare of Numpy Array with Python List

In [5]:
mList = list(range(0,1000000))
mArray = np.arange(0,1000000)

print("mArray ",type(mArray))
print("mList ",type(mList))

mArray  <class 'numpy.ndarray'>
mList  <class 'list'>


In [6]:
%time for i in range(10): newList = [ x*2 for x in mList]

Wall time: 1.33 s


In [7]:
%time for i in range(10): newArray = mArray*2

Wall time: 23.7 ms


# Numpy Array opr.

In [8]:
import numpy as np

In [9]:
mList = [11,22,33,44,55,66,77,88,99]

arr = np.array(mList)

In [10]:
print("Values in Array", arr)
print("Datatypes",type(arr))
print("Dimension / Depth of Array",arr.ndim)
print("Size of each Dimension", arr.shape)
print("Lenght of array", len(arr))

Values in Array [11 22 33 44 55 66 77 88 99]
Datatypes <class 'numpy.ndarray'>
Dimension / Depth of Array 1
Size of each Dimension (9,)
Lenght of array 9


In [16]:
arr

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [17]:
mulArr = arr*2
mulArr

array([ 22,  44,  66,  88, 110, 132, 154, 176, 198])

In [18]:
arr+100

array([111, 122, 133, 144, 155, 166, 177, 188, 199])

In [19]:
arr-9

array([ 2, 13, 24, 35, 46, 57, 68, 79, 90])

In [20]:
arr/100

array([0.11, 0.22, 0.33, 0.44, 0.55, 0.66, 0.77, 0.88, 0.99])

In [21]:
np.round(arr/100,1)

array([0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1. ])

In [23]:
print("Max", arr.max())
print("Min", arr.min())
print("Avg", arr.mean())
print("Sum", arr.sum())

Max 99
Min 11
Avg 55.0
Sum 495


# Types of Values in arrays

In [ ]:
# boolean ---> integer -----> float ---> str

In [29]:
mArr = np.array([11,22,True,False,31.34,'oracle',True,33,44])

print("Array Values",mArr)
print("Datatype of mArr", type(mArr))
print("Datatype of Values in mArr", mArr.dtype)

Array Values ['11' '22' 'True' 'False' '31.34' 'oracle' 'True' '33' '44']
Datatype of mArr <class 'numpy.ndarray'>
Datatype of Values in mArr <U32


# Search for Values in Arrays

In [30]:
mList = [11,22,33,44,55,66,77,88,99]

arr = np.array(mList)

In [31]:
arr 

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [32]:
arr > 50               # Returns a new boolean array with True at values satisfying the condition

array([False, False, False, False,  True,  True,  True,  True,  True])

In [33]:
arr[arr > 50 ]   # Returns a new value array with values satisfying the condition

array([55, 66, 77, 88, 99])

In [34]:
np.where(arr>50)   # Returns a new index array with values satisfying the condition

(array([4, 5, 6, 7, 8], dtype=int64),)

# Finance Data Analysis

In [49]:
# input data
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

revenue = np.array(revenue)
expenses = np.array(expenses)

print("Shape of Array revenue", revenue.shape)
print("Shape of Array expenses",expenses.shape)

Shape of Array revenue (12,)
Shape of Array expenses (12,)


In [50]:
# We need to calculate monthly profit for all months
monthly_profit = revenue-expenses
monthly_profit

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [51]:
# Calculate Profit after Tax (PAT), tax amount 30% on monthly profit for all months
PAT = monthly_profit-(monthly_profit*0.3)
PAT

array([ 1765.869,  1337.973, -2595.453, -2040.017,  -419.944,  5085.668,
        5747.385,  2761.479,  2329.873, -1567.055,   461.72 ,  8140.678])

In [55]:
# Calculate Profit Margin, PAT divided by revenue, calculate as percentage with 0 decimals
profitMargin = np.round(PAT/revenue*100).astype('int')
profitMargin

array([ 12,  18, -30, -22,  -5,  63,  50,  28,  23, -11,   4,  53])

# Slicing

In [56]:
letters = np.array(['a','b','c','d','e','f','g','h','i','j'])
letters

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='<U1')

In [ ]:
letters[:]            # everything in the array

In [ ]:
letters[::]            # everything in the array

In [ ]:
letters[2:]           # start 2   stop end of list   step 1

In [ ]:
letters[:7]           # start 0   stop 7   step 1

In [ ]:
letters[2:7]           # start 2   stop 7  step1

In [ ]:
letters[2:-4]           # start 2   stop -4  step 1

In [ ]:
letters[8:3:1]           # start 8    stop 3   step 1

In [ ]:
letters[8:3: -1]           # start 8   stop 3  step -1

In [ ]:
letters[::2]           # start 0   stop end of array   step 2

In [ ]:
letters[::3]           # start 0   stop end of array   step 3

In [ ]:
letters[::-1]           # reverse the array

In [ ]:
# everything in array except last value
letters[0 : -1 : 1]     # start 0   stop -1   step 1

In [ ]:
# everything in array except last value
letters[0:-1]     # start 0   stop -1   step 1

In [ ]:
# everything in array except last value
letters[:-1]     # start 0   stop -1   step 1

In [ ]:
# return last 5 elements in array

letters[-5:]     # start -5   stop end of list   step 1

In [63]:
letters[0]           # returns value at index 0 as string type variable

'a'

In [64]:
letters[0:1]         # returns value at index 0 as numpy array 

array(['a'], dtype='<U1')

In [65]:
letters[0::-1]

array(['a'], dtype='<U1')

# 2d Array / Matrix

In [66]:
arr = np.arange(20)  # 1d array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# newShape = (row,col) = row*col = 20

In [67]:
m1 = np.reshape(arr, (5,4))
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [73]:
m2 = np.array([[0,4,8,12],
               [16,1,5,9],
               [13,17,18,3],
               [7,11,15,19],
               [2,3,6,10]])
m2

array([[ 0,  4,  8, 12],
       [16,  1,  5,  9],
       [13, 17, 18,  3],
       [ 7, 11, 15, 19],
       [ 2,  3,  6, 10]])

In [79]:
zArr = np.zeros((3,6))
zArr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [81]:
zArr = np.zeros((3,6), dtype=int)
zArr

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [88]:
rArr = np.random.randn(6,3)
rArr.astype(int)

array([[ 1,  0,  0],
       [-1,  0,  0],
       [ 0,  0,  2],
       [ 0,  1,  0],
       [ 1,  0,  0],
       [ 1,  0, -1]])

In [86]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [87]:
arr.T                 # Transpose , convert rows to columns and vice versa

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])